### ISSUE TITLE
add README

### ISSUE THREAD

**Issue by Parikshit-Hooda** [datenanfragen/letter-generator#1]
Hi! I would love to take up this issue as part of hacktoberfest!

**Comment by baltpeter** [comment]
Sure, please do. It would be great to have a minimum working example of the code for others to use.

**Comment by Schokobecher** [comment]
It's been a year, I think @Parikshit-Hooda has given up?

**Comment by baltpeter** [comment]
Good point, @Schokobecher. If you or anyone else wants to take this up, feel free.

**Comment by romain325** [comment]
Hi I can do it for this year HacktoberFest !

**Comment by baltpeter** [comment]
Sure, @romain325. I have assigned you.
